baseURL = "https://disk128.netlify.app/"
languageCode = "fr"
title = "Disk128"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "fr"
enableEmoji = true
paginate = 20
googleAnalytics = "G-MEASUREMENT_DCES535JJN"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
